#!/usr/bin/env bash
# Regenerate BrickBack/Config/Secrets.xcconfig (gitignored) from the Flutter app's
# .env — the single source of truth for the five publishable config values.
# See docs/ios-swift/01-foundation.md (S0). Publishable keys only; no server secrets.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$HERE/../mobile/.env"
OUT="$HERE/BrickBack/Config/Secrets.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: $ENV_FILE not found (copy the five values from the Flutter .env)" >&2
  exit 1
fi

# Read a KEY=value line from .env (value may contain '='). Strip any unquoted inline
# ` # comment` and surrounding whitespace (dotenv semantics) so trailing notes like
# "# ⟵ SET ME" don't leak into the value.
val() {
  grep -E "^$1=" "$ENV_FILE" | head -1 | cut -d= -f2- \
    | sed -E 's/[[:space:]]+#.*$//' \
    | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//'
}

# xcconfig treats '//' as a comment; split the scheme's two slashes with an empty
# $() so 'https://host' survives as a literal.
esc_url() { printf '%s' "$1" | sed 's#://#:/$()/#'; }

USER_URL="$(esc_url "$(val USER_SUPABASE_URL)")"
USER_KEY="$(val USER_SUPABASE_ANON_KEY)"
CAT_URL="$(esc_url "$(val CATALOG_SUPABASE_URL)")"
CAT_KEY="$(val CATALOG_SUPABASE_ANON_KEY)"
CDN="$(esc_url "$(val CDN_URL)")"

cat > "$OUT" <<EOF
// GENERATED by apps/ios/gen-secrets.sh from apps/mobile/.env — do not edit by hand.
// Gitignored. Publishable/client-safe values only.

USER_SUPABASE_URL = $USER_URL
USER_SUPABASE_ANON_KEY = $USER_KEY
CATALOG_SUPABASE_URL = $CAT_URL
CATALOG_SUPABASE_ANON_KEY = $CAT_KEY
CDN_URL = $CDN
EOF

echo "wrote $OUT"
