import Foundation

/// Typed access to every localized UI string (S7 i18n). GENERATED by
/// `apps/ios/scripts/gen_l10n.py` from the compact table — edit the table + regenerate,
/// don't hand-edit. Each accessor resolves against `I18n.bundle`/`I18n.locale`, so the in-app
/// Language override switches strings live (see `LocaleController`). Keys mirror
/// `Localizable.xcstrings`.
enum L {
    private static func s(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: I18n.bundle, locale: I18n.locale)
    }

    static var navRebuilds: String { s("navRebuilds") }
    static var navParty: String { s("navParty") }
    static var navProfile: String { s("navProfile") }
    static var couldntLoad: String { s("couldntLoad") }
    static var ok: String { s("ok") }
    static var cancel: String { s("cancel") }
    static var done: String { s("done") }
    static var remove: String { s("remove") }
    static var unknownColor: String { s("unknownColor") }
    static var noMatches: String { s("noMatches") }
    static var everyPartAccountedFor: String { s("everyPartAccountedFor") }
    static var rebuildGone: String { s("rebuildGone") }
    static var addASet: String { s("addASet") }
    static var homeEmptyTitle: String { s("homeEmptyTitle") }
    static var homeEmptyMessage: String { s("homeEmptyMessage") }
    static var homeNoMatchTitle: String { s("homeNoMatchTitle") }
    static var homeNoMatchMessage: String { s("homeNoMatchMessage") }
    static var clearFilter: String { s("clearFilter") }
    static var filterSets: String { s("filterSets") }
    static func filterSetsActive(_ count: Int) -> String {
        String(localized: "filterSetsActive", defaultValue: "\(count) active", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var continueBuilding: String { s("continueBuilding") }
    static var allSets: String { s("allSets") }
    static var verifiedBadge: String { s("verifiedBadge") }
    static var filter: String { s("filter") }
    static var close: String { s("close") }
    static var statusLabel: String { s("statusLabel") }
    static var themeLabel: String { s("themeLabel") }
    static var themeFilterHint: String { s("themeFilterHint") }
    static var clearAll: String { s("clearAll") }
    static var filterAll: String { s("filterAll") }
    static var filterIncomplete: String { s("filterIncomplete") }
    static var filterComplete: String { s("filterComplete") }
    static func partsHaveTotal(have: Int, total: Int) -> String {
        String(localized: "partsHaveTotal", defaultValue: "\(have) / \(total) parts", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func completeParts(_ count: Int) -> String {
        String(localized: "completeParts", defaultValue: "Complete · \(count) parts", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func partsProgress(have: Int, total: Int, pct: Int) -> String {
        String(localized: "partsProgress", defaultValue: "\(have) / \(total) parts · \(pct)%", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var searchHint: String { s("searchHint") }
    static var searchEmptyTitle: String { s("searchEmptyTitle") }
    static var searchEmptyMessage: String { s("searchEmptyMessage") }
    static var searchFailed: String { s("searchFailed") }
    static var searchNoMatchesMessage: String { s("searchNoMatchesMessage") }
    static func partsCount(_ count: Int) -> String {
        String(localized: "partsCount", defaultValue: "\(count) parts", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var setHeader: String { s("setHeader") }
    static var setCouldntLoad: String { s("setCouldntLoad") }
    static var uniqueParts: String { s("uniqueParts") }
    static var minifigs: String { s("minifigs") }
    static var startSorting: String { s("startSorting") }
    static var startSortingHint: String { s("startSortingHint") }
    static var couldntAddSet: String { s("couldntAddSet") }
    static var partsCouldntLoad: String { s("partsCouldntLoad") }
    static var partsEmptyTitle: String { s("partsEmptyTitle") }
    static var partsEmptyMessage: String { s("partsEmptyMessage") }
    static func uniquePartsCount(_ count: Int) -> String {
        String(localized: "uniquePartsCount", defaultValue: "\(count) unique parts", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var minifigsCouldntLoad: String { s("minifigsCouldntLoad") }
    static var minifigsEmptyTitle: String { s("minifigsEmptyTitle") }
    static var minifigsEmptyMessage: String { s("minifigsEmptyMessage") }
    static var signInTitle: String { s("signInTitle") }
    static var signInHeadline: String { s("signInHeadline") }
    static var signInSubtitle: String { s("signInSubtitle") }
    static var continueWithGoogle: String { s("continueWithGoogle") }
    static var emailHint: String { s("emailHint") }
    static var emailSignInLink: String { s("emailSignInLink") }
    static var emailSentConfirm: String { s("emailSentConfirm") }
    static var signInFooter: String { s("signInFooter") }
    static var emailInvalid: String { s("emailInvalid") }
    static var appleNoToken: String { s("appleNoToken") }
    static var orDivider: String { s("orDivider") }
    static var cloudSyncTitle: String { s("cloudSyncTitle") }
    static var premiumBadge: String { s("premiumBadge") }
    static var paywallHeadline: String { s("paywallHeadline") }
    static var turnOnCloudSync: String { s("turnOnCloudSync") }
    static var paywallCtaHint: String { s("paywallCtaHint") }
    static var benefitSyncTitle: String { s("benefitSyncTitle") }
    static var benefitSyncBody: String { s("benefitSyncBody") }
    static var benefitUnlimitedTitle: String { s("benefitUnlimitedTitle") }
    static var benefitUnlimitedBody: String { s("benefitUnlimitedBody") }
    static var benefitBackupTitle: String { s("benefitBackupTitle") }
    static var benefitBackupBody: String { s("benefitBackupBody") }
    static var partyModeTitle: String { s("partyModeTitle") }
    static var benefitPartyBody: String { s("benefitPartyBody") }
    static var profileSubtitle: String { s("profileSubtitle") }
    static var statSetsBuilt: String { s("statSetsBuilt") }
    static var statPartsCollected: String { s("statPartsCollected") }
    static var nameLabel: String { s("nameLabel") }
    static var nameEditorTitle: String { s("nameEditorTitle") }
    static var nameEditorSubtitle: String { s("nameEditorSubtitle") }
    static var nameEditorHint: String { s("nameEditorHint") }
    static var shuffleName: String { s("shuffleName") }
    static var save: String { s("save") }
    static var premium: String { s("premium") }
    static var active: String { s("active") }
    static var free: String { s("free") }
    static var syncNow: String { s("syncNow") }
    static var language: String { s("language") }
    static var languageSystem: String { s("languageSystem") }
    static var languageEnglish: String { s("languageEnglish") }
    static var languageLithuanian: String { s("languageLithuanian") }
    static var appearance: String { s("appearance") }
    static var themeSystem: String { s("themeSystem") }
    static var themeLight: String { s("themeLight") }
    static var themeDark: String { s("themeDark") }
    static var signedIn: String { s("signedIn") }
    static var yourAccount: String { s("yourAccount") }
    static var signOut: String { s("signOut") }
    static var notSignedIn: String { s("notSignedIn") }
    static var profileSignInPrompt: String { s("profileSignInPrompt") }
    static var partyModeBody: String { s("partyModeBody") }
    static var partyJoinTitle: String { s("partyJoinTitle") }
    static var partyTabSubtitle: String { s("partyTabSubtitle") }
    static var partyHostNote: String { s("partyHostNote") }
    static var countNoInventoryTitle: String { s("countNoInventoryTitle") }
    static var countNoInventoryMessage: String { s("countNoInventoryMessage") }
    static var countAllSortedTitle: String { s("countAllSortedTitle") }
    static func countHaveOfPartsTypes(have: Int, total: Int, types: Int) -> String {
        String(localized: "countHaveOfPartsTypes", defaultValue: "\(have) of \(total) parts · \(types) types", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var moreActions: String { s("moreActions") }
    static var closeActions: String { s("closeActions") }
    static var menuReview: String { s("menuReview") }
    static var menuStartParty: String { s("menuStartParty") }
    static var menuSearchParts: String { s("menuSearchParts") }
    static var sortParty: String { s("sortParty") }
    static var couldntStartParty: String { s("couldntStartParty") }
    static var allAccountedFor: String { s("allAccountedFor") }
    static var step: String { s("step") }
    static var viewOnBrickLink: String { s("viewOnBrickLink") }
    static var countSearchHint: String { s("countSearchHint") }
    static var countNoMatchesMessage: String { s("countNoMatchesMessage") }
    static var groupByColor: String { s("groupByColor") }
    static var groupByType: String { s("groupByType") }
    static var groupByStatus: String { s("groupByStatus") }
    static var groupByNone: String { s("groupByNone") }
    static var viewSettings: String { s("viewSettings") }
    static var groupBy: String { s("groupBy") }
    static var remainingOnly: String { s("remainingOnly") }
    static var remainingOnlyHint: String { s("remainingOnlyHint") }
    static var showExtras: String { s("showExtras") }
    static var showExtrasBody: String { s("showExtrasBody") }
    static var noExtras: String { s("noExtras") }
    static var sectionAllParts: String { s("sectionAllParts") }
    static var sectionRemaining: String { s("sectionRemaining") }
    static var sectionComplete: String { s("sectionComplete") }
    static var sectionExtras: String { s("sectionExtras") }
    static var sectionOther: String { s("sectionOther") }
    static var missingParts: String { s("missingParts") }
    static var reviewNothingMissing: String { s("reviewNothingMissing") }
    static func reviewPartsFound(found: Int, needed: Int) -> String {
        String(localized: "reviewPartsFound", defaultValue: "\(found) of \(needed) parts found", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var allPartsAccountedFor: String { s("allPartsAccountedFor") }
    static var minifiguresSection: String { s("minifiguresSection") }
    static var viewReport: String { s("viewReport") }
    static var reverify: String { s("reverify") }
    static var markAsVerified: String { s("markAsVerified") }
    static func typesStillMissing(_ n: Int) -> String {
        String(localized: "typesStillMissing", defaultValue: "\(n) types still missing", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func typeCount(_ n: Int) -> String {
        String(localized: "typeCount", defaultValue: "\(n) types", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func notExportableText(_ n: Int) -> String {
        String(localized: "notExportableText", defaultValue: "\(n) parts have no BrickLink mapping and won't be in the export.", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func needQty(_ qty: Int) -> String {
        String(localized: "needQty", defaultValue: "need \(qty)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func minifigPresent(have: Int, needed: Int) -> String {
        String(localized: "minifigPresent", defaultValue: "\(have) of \(needed) present", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var neededOne: String { s("neededOne") }
    static func pctAllParts(_ pct: Int) -> String {
        String(localized: "pctAllParts", defaultValue: "\(pct)% — all parts", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func pctOfParts(_ pct: Int) -> String {
        String(localized: "pctOfParts", defaultValue: "\(pct)% of parts", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var noMinifigures: String { s("noMinifigures") }
    static var minifiguresIncluded: String { s("minifiguresIncluded") }
    static var minifiguresIncomplete: String { s("minifiguresIncomplete") }
    static var whatElseInBox: String { s("whatElseInBox") }
    static var boxIncluded: String { s("boxIncluded") }
    static var instructionsIncluded: String { s("instructionsIncluded") }
    static var stickersApplied: String { s("stickersApplied") }
    static var notesOptional: String { s("notesOptional") }
    static var notesHint: String { s("notesHint") }
    static var saveVerification: String { s("saveVerification") }
    static var notVerifiedYet: String { s("notVerifiedYet") }
    static var notVerifiedMessage: String { s("notVerifiedMessage") }
    static var shareImage: String { s("shareImage") }
    static var sharePdf: String { s("sharePdf") }
    static func reportPctComplete(_ pct: Int) -> String {
        String(localized: "reportPctComplete", defaultValue: "\(pct)% COMPLETE", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func reportPctPartsMissing(pct: Int, count: Int) -> String {
        String(localized: "reportPctPartsMissing", defaultValue: "\(pct)% · \(count) parts missing", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var noneInSet: String { s("noneInSet") }
    static var inventoryVerification: String { s("inventoryVerification") }
    static var reportPartsFound: String { s("reportPartsFound") }
    static var allPartsPresent: String { s("allPartsPresent") }
    static func verifiedDate(_ date: String) -> String {
        String(localized: "verifiedDate", defaultValue: "Verified \(date)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var verifiedWithBrickback: String { s("verifiedWithBrickback") }
    static var couldntLoadParty: String { s("couldntLoadParty") }
    static var endThisParty: String { s("endThisParty") }
    static var endParty: String { s("endParty") }
    static var endPartyBody: String { s("endPartyBody") }
    static var statusEnded: String { s("statusEnded") }
    static var statusPaused: String { s("statusPaused") }
    static func partyCodeCaption(_ code: String) -> String {
        String(localized: "partyCodeCaption", defaultValue: "Party · code \(code)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func partyProgress(have: Int, total: Int) -> String {
        String(localized: "partyProgress", defaultValue: "\(have) of \(total) parts", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var addFoundParts: String { s("addFoundParts") }
    static var activity: String { s("activity") }
    static var noActivity: String { s("noActivity") }
    static var invite: String { s("invite") }
    static func memberCount(_ n: Int) -> String {
        String(localized: "memberCount", defaultValue: "\(n) members", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func activityLine(who: String, what: String) -> String {
        String(localized: "activityLine", defaultValue: "\(who) added \(what)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var roleHost: String { s("roleHost") }
    static var roleMember: String { s("roleMember") }
    static var someone: String { s("someone") }
    static var partyJoinSubtitle: String { s("partyJoinSubtitle") }
    static var partyJoinCta: String { s("partyJoinCta") }
    static var partyJoinError: String { s("partyJoinError") }
    static func inviteTitle(_ name: String) -> String {
        String(localized: "inviteTitle", defaultValue: "Invite to \(name)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var inviteSubtitle: String { s("inviteSubtitle") }
    static var joinCode: String { s("joinCode") }
    static var shareInvite: String { s("shareInvite") }
    static func partyShareText(code: String, link: String) -> String {
        String(localized: "partyShareText", defaultValue: "Join my BrickBack sort party — code \(code)\n\(link)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var partyNothingLeftTitle: String { s("partyNothingLeftTitle") }
    static func addLabel(_ n: Int) -> String {
        String(localized: "addLabel", defaultValue: "Add \(n) parts", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func partyRemainingLabel(color: String, count: Int) -> String {
        String(localized: "partyRemainingLabel", defaultValue: "\(color) · \(count) left", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func couldntAddParts(_ error: String) -> String {
        String(localized: "couldntAddParts", defaultValue: "Couldn't add parts: \(error)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static var a11yProgress: String { s("a11yProgress") }
    static var a11yStartParty: String { s("a11yStartParty") }
    static var a11yDetails: String { s("a11yDetails") }
    static var a11yAdd: String { s("a11yAdd") }
    static var a11yPresent: String { s("a11yPresent") }
    static var a11yAbsent: String { s("a11yAbsent") }
    static var a11yTileAddHint: String { s("a11yTileAddHint") }
    static var a11yOpensBrickLink: String { s("a11yOpensBrickLink") }
    static func a11yNameColor(name: String, color: String) -> String {
        String(localized: "a11yNameColor", defaultValue: "\(name), \(color)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func a11yCount(have: Int, needed: Int) -> String {
        String(localized: "a11yCount", defaultValue: "\(have) of \(needed)", bundle: I18n.bundle, locale: I18n.locale)
    }
    static func a11yCountComplete(have: Int, needed: Int) -> String {
        String(localized: "a11yCountComplete", defaultValue: "\(have) of \(needed), complete", bundle: I18n.bundle, locale: I18n.locale)
    }
}
